### ISSUE TITLE
Where do you keep the platform specific code

### ISSUE THREAD

**Issue by ooxi** [ataradov/free-dap#12]
The free-dap platform directories contain a lot of infrastructure code e.g. [usart.c](https://github.com/ataradov/free-dap/blob/master/platform/samd11_vcp/uart.c). Was this code specifically written for free-dap, or do you keep souce code somewhere else?

I looked at your [mcu-starter-projects](https://github.com/ataradov/mcu-starter-projects/tree/master/samd11) repository but couldn't find it anywhere else.

Reason I'm asking is, I want to extend samd21 platform with USART functionality and don't want to reinvent the wheel.

**Comment by ataradov** [comment]
All my code is written specifically for the project. I may borrow from older projects if I know that I wrote something similar already.  It is not worth it to create a universal driver, when targeted driver here is just 200 lines of code.

In general, a couple projects that contain a lot of useful sample code are https://github.com/ataradov/siggen and https://github.com/ataradov/dgw. I borrow from them a lot.

**Comment by ooxi** [comment]
Thank you!
