### ISSUE TITLE
TDO/TDI?

### ISSUE THREAD

**Issue by koendv** [ataradov/free-dap#19]
in dap.c I find:
```
  if (select & DAP_SWJ_TDI)
    DAP_CONFIG_TDO_write(value & DAP_SWJ_TDI);
```
but I do not find a HAL_GPIO_TDO_out()
This is strange.

**Comment by ataradov** [comment]
While functions are present, otherwise things will not build, the write must actually happen to TDI, not TDO. The pins are marked from the target point of view.

I fixed that.

**Comment by koendv** [comment]
Thank you. Will be using free-dap with Sipeed Longan Nano, GD32VF103 processor.
Happy Christmas.
