### ISSUE TITLE
SWO support

### ISSUE THREAD

**Issue by BogdanTheGeek** [ataradov/free-dap#36]
Is there any interest in supporting SWO for bi-directional coms without uart?
There are a couple of implementations floating around, but I'm not sure if they have any limitations.
https://arm-software.github.io/CMSIS-DAP/latest/group__DAP__swo__gr.html

**Comment by ataradov** [comment]
SWO is one way only (from the MCU). I have no interest in supporting that. I personally find very little value in SWO and it will increase overall complexity.

**Comment by BogdanTheGeek** [comment]
ok, thanks for the response and the great work on the project!
