### ISSUE TITLE
Expected flashing speed

### ISSUE THREAD

**Issue by ooxi** [ataradov/free-dap#7]
I'm using free-dap on a SAMD11 in order to flash microcontrollers and it works remarkably well except for the speed. The process of programming and verifying a 128K ROM takes about 20 seconds.

I'm wondering what's the limit here:

* The speed of the SAMD11 used for bit banging? I see you are already using [DFLL to run at 48 MHz](https://github.com/ataradov/free-dap/blob/master/platform/samd11/main.c#L89). According to the [datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-42363-SAM-D11_Datasheet.pdf) there's also a FDPLL96M mode to run at 96 MHz, however I don't know what the fractional part is about
* The speed of data transferred from PC to SAMD via USB?
* The write speed of the flash itself (tried SAMD21E, G and J)

Before investing in any solution I wanted to make sure I'm not missing something obvious here. Is 20s a reasonable speed for 128K program + verify or should it be much faster anyhow?

**Comment by ataradov** [comment]
128K  device contains 512 rows and 2048 pages. Programming time for the device variant A is 512 * 6 ms + 2048 * 2.5 ms = 8192 ms = 8.2 seconds. Variants B and C are a bit faster at erase and their programming time is 512 * 1.2 ms + 2048 * 2.5 ms = 5.7 seconds.

The rest s mostly defined by the USB HID. On USB FS, HID can only do 64 KBytes per second of sustained bandwidth, but in this case we send small frames (polling for flags) a lot. And it can only send one 64 byte frame in 1 ms interval. This is a significant source of the delay.

Interface bit-banging is pretty fast. D11 already runs at 48 MHz and bit-banging happens as fast as possible without going into asm and rewriting the whole routines. But that won't make things much faster anyway. You may shave 1-2 seconds, no more.

**Comment by ataradov** [comment]
Estimated number of USB HID frames exchanged (command + response) per 256-byte sector:
Write address = 2
Write unlock command = 2
Read INTFLAG = 2
Write erase row command = 2
Read INTFLAG = 2
Write block = 10

Total = 20

Time to execute the command is 1 ms, so it will take 20 ms per row or 20 * 512 = 10240 ms = 10.2 seconds. This is just to transfer the data and comands.

**Comment by ataradov** [comment]
USB HS can be much faster, and that's why recent $15 Microchip programmer is based on SAME70, even though there is absolutely no need for such a powerful device in a programmer. USB is also only available only in 100-pin variant, so you end up paying quite a bit.

**Comment by ooxi** [comment]
Thanks for the elaborate feedback! Could you elaborate on the speed differences between device variant A and B/C? Are you talking about Chip revisions of the target to be programmed?

When transferring the data to be programmed via USB HID takes about 10s and has to be transferred twice (once for programming, once for verification) this more or less explains the time I'm seeing. USB mass storage looks like a promising alternative, however it needs enough ROM/RAM on the chip to be useful.

Could you point me to the $15 Microchip programmer you are talking about? Such a low cost device would be quite handy since the alternative are multi hundred dollar Segger devices.

**Comment by ataradov** [comment]
Revisions of the target chip. The numbers are taken from the SAM D21 datasheet. See tables 37-43 and 37-44. 

MSD is a horrible alternative. It is easier to get $20 LPC-Link 2 and set it to CMSIS-DAP mode. This will maintain full compatibility with your tools, but you will bed the best CMSIS-DAP programmer on the market.

The tool I'm talking about is MPLAB Snap -  http://www.microchip.com/developmenttools/ProductDetails/PartNO/PG164100

But it uses a proprietary protocol on the USB side, so it won't work with anything but MPLAB.

**Comment by ooxi** [comment]
Thank you for your feedback!

**Comment by ataradov** [comment]
If you have a master CPU capable of running any code and a bit of bit-banging, then this is the better solution - https://github.com/ataradov/embedded-swd . No need to have the intermediate layers at all.
